//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Conceptual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor : Person
    {
        public string CodProfessor { get; set; }
    }
}
